export const types = {
    CHANGE_TITLE: 'CHANGE_TITLE',
    WITH_PARAMS: 'WITH_PARAMS',
    FROM_INPUT: 'FROM_INPUT',
    ADD_TASK: 'ADD_TASK',
    TOGGLE_TASK: 'TOGGLE_TASK',
    SEARCH_USERS_REQUEST: 'SEARCH_USERS_REQUEST',
    SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
    SEARCH_USERS_FAILURE: 'SEARCH_USERS_FAILURE'
}